### ISSUE TITLE
TimeoutError: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by shisheidexinya** [VITA-Group/FSGS#27]
Thank you for your nice work!
I used cuda 11.6 pytorch 1.12.1, but  I got a CUDA error: an illegal memory access was encountered.
So I use cuda11.7 pytorch 1.13.0 , torchvision 0.14.0, torchaudio 0.13.0.
and I get a TimeoutError ,  I wonder what's going on?

(FSGS) root@autodl-container-7ac146ab4e-87edd0e7:~/autodl-tmp/FSGS-main#  python train.py --source_path bicycle --model_path output/bicycle --eval  --n_views 24 --depth_pseudo_weight 0.03
Traceback (most recent call last):
  File "/root/miniconda3/envs/FSGS/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/root/miniconda3/envs/FSGS/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/root/miniconda3/envs/FSGS/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/root/miniconda3/envs/FSGS/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/miniconda3/envs/FSGS/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/root/miniconda3/envs/FSGS/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/root/miniconda3/envs/FSGS/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/root/miniconda3/envs/FSGS/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/root/miniconda3/envs/FSGS/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/root/miniconda3/envs/FSGS/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 25, in <module>
    from utils.depth_utils import estimate_depth
  File "/root/autodl-tmp/FSGS-main/utils/depth_utils.py", line 3, in <module>
    midas = torch.hub.load("intel-isl/MiDaS", "DPT_Hybrid")
  File "/root/miniconda3/envs/FSGS/lib/python3.8/site-packages/torch/hub.py", line 539, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "/root/miniconda3/envs/FSGS/lib/python3.8/site-packages/torch/hub.py", line 180, in _get_cache_or_reload
    repo_owner, repo_name, ref = _parse_repo_info(github)
  File "/root/miniconda3/envs/FSGS/lib/python3.8/site-packages/torch/hub.py", line 134, in _parse_repo_info
    with urlopen(f"https://github.com/{repo_owner}/{repo_name}/tree/main/"):
  File "/root/miniconda3/envs/FSGS/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/root/miniconda3/envs/FSGS/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/root/miniconda3/envs/FSGS/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/root/miniconda3/envs/FSGS/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/root/miniconda3/envs/FSGS/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/root/miniconda3/envs/FSGS/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/root/miniconda3/envs/FSGS/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/root/miniconda3/envs/FSGS/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/root/miniconda3/envs/FSGS/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/root/miniconda3/envs/FSGS/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/root/miniconda3/envs/FSGS/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

**Comment by zehaozhu** [comment]
You can just download the checkpoint of DPT model from https://github.com/isl-org/MiDaS and save it to the cache dir.

**Comment by shisheidexinya** [comment]
Thanks for you reply.
I solved this problem.
Best wishes to you!

**Comment by Yuhuoo** [comment]
Can you tell me in which specific directory I should put it?

**Comment by shisheidexinya** [comment]
- Use the installation package given by the author can be used, when you
   use DPT can not use the domestic network, you need to use vpn.

**Comment by heandrea** [comment]
> 您能告诉我应该把它放在哪个特定的目录中吗？

Excuse me, have you solved it? I've encountered the same problem too.

**Comment by lywudi** [comment]
> Can you tell me in which specific directory I should put it?你能告诉我应该把它放在哪个目录下吗？

你好，我也遇到了这个问题请问你解决了吗

**Comment by heandrea** [comment]
> > Can you tell me in which specific directory I should put it?你能告诉我应该把它放在哪个目录下吗？
> 
> 你好，我也遇到了这个问题请问你解决了吗

yes,dowmload the files and put it in the  /root/.cache/torch/hub/(note the path!!!)， and change the code below(in utils/depth_utils.py):


midas = torch.hub.load("/root/.cache/torch/hub/intel-isl/MiDaS", "DPT_Hybrid","/root/.cache/torch/hub/intel-isl/MiDaS/checkpoints/dpt_hybrid_384.pt",source='local')
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
midas.to(device)
midas.eval()
for param in midas.parameters():
    param.requires_grad = False

#torch.hub.set_dir('/root/.cache/torch/hub')
midas_transforms = torch.hub.load("/root/.cache/torch/hub/intel-isl/MiDaS", "transforms",source="local")
